-- ============================================================================
-- Pre-create the per-tenant crm_<cod_agente> tables in THIS project, seeded
-- from leads.ai_agent_enabled, ahead of pointing the n8n conversation-path
-- nodes here.
--
-- Context: the n8n agent workflows read and write per-tenant state in tables
-- named crm_<whatsapp_number>. Those tables lived in the pre-migration Supabase
-- project; none existed here (verified across all schemas on 2026-08-14).
-- public.messages had had no write since 2026-08-04 while the agent workflows
-- executed hundreds of times without error, which is how the split was
-- confirmed: a conversation path that runs clean and records nothing is not
-- working, it is writing somewhere else.
--
-- Repointing the nodes without this step would let the workflows' own
-- "If Error - Create Table" fallback create these tables EMPTY. An empty
-- crm_ table means no agent_on_off row for any lead, so leads that an operator
-- switched off would be treated as on and the agent would resume messaging
-- them. 154 leads across 55 tenants were off at the time.
--
-- leads.ai_agent_enabled is the application's own source of truth for that
-- flag and lives here, so the flag was recoverable without touching the old
-- project. Conversation memory (n8n_<cod_agente>) is NOT recoverable this way
-- and was knowingly reset.
--
-- Schema mirrors the CREATE TABLE in the workflows' fallback node exactly.
-- ============================================================================

DO $$
declare
  r record;
  tbl text;
  seeded integer;
  total_tables integer := 0;
  total_rows integer := 0;
begin
  for r in
    select p.id as user_id, p.whatsapp_number as cod
    from public.profiles p
    -- Digits only. One profile stored its number with a space in it, which is
    -- not a usable table identifier and never had a table in the old project
    -- either, so it is skipped here as well.
    where p.whatsapp_number ~ '^[0-9]+$'
  loop
    tbl := 'crm_' || r.cod;

    execute format(
      'create table if not exists public.%I (
         id bigint generated by default as identity not null,
         created_at timestamp with time zone not null default now(),
         phone text null,
         agent_on_off text null,
         name text null,
         last_msg_timestamp text null,
         constraint %I primary key (id)
       )', tbl, tbl || '_pkey');

    -- RLS on with no policy: service_role only, same as the fallback node.
    execute format('alter table public.%I enable row level security', tbl);

    -- last_msg_timestamp is left null on purpose. Its text format is written
    -- by n8n and is not reproducible from here; null is what a freshly created
    -- table would hold anyway, so this is no worse than the fallback path.
    execute format(
      'insert into public.%I (phone, agent_on_off, name)
       select l.phone,
              case when l.ai_agent_enabled then ''ON'' else ''OFF'' end,
              l.name
       from public.leads l
       where l.user_id = %L
         and l.phone is not null
         and l.phone <> ''''
         and not exists (
           select 1 from public.%I x where x.phone = l.phone
         )', tbl, r.user_id, tbl);

    get diagnostics seeded = row_count;
    total_tables := total_tables + 1;
    total_rows := total_rows + seeded;
  end loop;

  raise notice 'crm tables ensured: %, rows seeded: %', total_tables, total_rows;
end;
$$;
